export const C = {
  blue: '#2563EB',
  blueLight: '#EFF6FF',
  blueMid: '#DBEAFE',
  green: '#16A34A',
  greenLight: '#F0FDF4',
  greenMid: '#DCFCE7',
  amber: '#D97706',
  amberLight: '#FFFBEB',
  amberMid: '#FEF3C7',
  red: '#DC2626',
  redLight: '#FEF2F2',
  redMid: '#FEE2E2',
  gray: '#64748B',
  grayLight: '#F8FAFC',
  grayBorder: '#E2E8F0',
  sidebar: '#0F172A',
  sidebarText: '#94A3B8',
  sidebarActive: '#2563EB',
  white: '#FFFFFF',
  text: '#1E293B',
  textMid: '#475569',
  textLight: '#94A3B8',
};

export const STATUS = {
  Available:            { bg: C.greenLight, text: C.green,   dot: C.green,   label: 'Available' },
  Charging:             { bg: C.blueLight,  text: C.blue,    dot: C.blue,    label: 'Charging' },
  Preparing:            { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'Preparing' },
  Suspended:            { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'Suspended' },
  Finishing:            { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'Finishing' },
  Faulted:              { bg: C.redLight,   text: C.red,     dot: C.red,     label: 'Faulted' },
  Offline:              { bg: '#F1F5F9',    text: '#64748B', dot: '#94A3B8', label: 'Offline' },
  Active:               { bg: C.blueLight,  text: C.blue,    dot: C.blue,    label: 'Active' },
  Completed:            { bg: C.greenLight, text: C.green,   dot: C.green,   label: 'Completed' },
  Paid:                 { bg: C.greenLight, text: C.green,   dot: C.green,   label: 'Paid' },
  Pending:              { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'Pending' },
  PaymentFailed:        { bg: C.redLight,   text: C.red,     dot: C.red,     label: 'Failed' },
  PaymentMethodMissing: { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'No Card' },
  BelowMinimum:         { bg: '#F1F5F9',    text: '#64748B', dot: '#94A3B8', label: '< Min' },
  Refunded:             { bg: C.amberLight, text: C.amber,   dot: C.amber,   label: 'Refunded' },
};
